image: archlinux
packages:
  - go-ipfs
  - leiningen
  - postgresql
sources:
  - https://github.com/ComLake/core
tasks:
  - init: |
      ipfs init
      systemctl --user enable ipfs.service
  - test: |
      cd core
      lein cloverage
environment:
  LEIN_SNAPSHOTS_IN_RELEASE: 1
