image: debian/buster
arch: amd64
packages:
  - leiningen
  - postgresql
sources:
  - https://github.com/ComLake/comlake.core
tasks:
  - ipfs: |
      curl \
        https://dist.ipfs.io/go-ipfs/v0.8.0/go-ipfs_v0.8.0_linux-amd64.tar.gz |
        tar xvz
      sudo go-ipfs/install.sh
      rm -r go-ipfs
      ipfs init
  - psql: |
      echo host all build 127.0.0.1/32 password |
        sudo tee -a /etc/postgresql/*/main/pg_hba.conf
      sudo -u postgres psql < comlake.core/resources/psql/auth.sql
      sudo -u postgres psql < comlake.core/resources/psql/db.sql
      sudo -u postgres psql comlake < comlake.core/resources/psql/table.sql
  - test: |
      ipfs daemon &
      cd comlake.core
      lein cloverage
  - jar: |
      cd comlake.core
      lein uberjar
artifacts:
  - comlake.core/target/uberjar/comlake.core-0.4.2-SNAPSHOT-standalone.jar
environment:
  LEIN_SNAPSHOTS_IN_RELEASE: 1
