@startuml
left to right direction

entity content {
    * cid : text
    --
    * type : text
    * extra : jsonb
}

entity dataset {
    * id : bigserial <<generated>>
    --
    * content : bigint <<foreign key>>
    * description : text
    * source : text
    * topics : text[]
    * extra : jsonb
    parent : bigint <<foreign key>>
}

dataset }o..|| content
@enduml
