@startuml
node Core {
    component Database as meta
    component FileSystem as files
    component HttpHandler as http
    component Extractor as extract
}

collections IPFS <<DFS>>
files <--> IPFS

database PostgreSQL <<DBMS>>
meta <--> PostgreSQL

http <--> files
http <--> meta
http <-right- extract
extract <-down- files
extract <-down-> meta

cloud "Public API and Query Engine" as client
client <--> http : HTTP
@enduml
