@startuml
left to right direction

:Admin:
:Other service: as Other
:Storage: as DFS
:Database: as DB

(Upload content) as upload
Other --> upload
upload -- DFS
upload -- DB

(Add dataset) as add
Other --> add
add -- DB

(Find datasets) as filter
Other --> filter
filter -- DB

(Download content) as download
Other --> download
download -- DFS

(Extract content) as extract
Other --> extract
extract -- DFS
extract -- DB

(Gather logs) as feed
Admin --> feed
@enduml
