@startuml
(*) --> "POST /file" as save
(*) --> "POST /dir" as mkdir
save --> "POST /cp" as cp
mkdir --> cp
cp --> "POST /dataset" as add
save --> add
cp --> "POST /update" as update
save --> update

(*) --> "POST /find" as find
find --> "GET /ls/{cid}"
find --> "GET /get/{cid}"
find --> "GET /schema/{cid}"
find --> "POST /extract/{cid}"
@enduml
